import { Component } from '@angular/core';
import { MatTableDataSource } from '@angular/material/table';

@Component({
  selector: 'adr-ibrelleu-projects',
  templateUrl: './ibrelleu-projects.component.html',
  styleUrl: './ibrelleu-projects.component.scss',
})
export class IbrelleuProjectsComponent {
  dataSource = new MatTableDataSource();

  columnsDisplayed: string[];

  columnsSchema: any;

  constructor() {
    this.columnsSchema = [
      {
        key: 'ibrelleuProjectName',
        type: 'url',
      },
      {
        key: 'projectStatus',
        type: 'readOnly',
      },
      {
        key: 'mainSector',
        type: 'readOnly',
      },
      {
        key: 'mainActivity',
        type: 'readOnly',
      },
      {
        key: 'totalEconomicSituation',
        type: 'money',
      },
      {
        key: 'consultant',
        type: 'readOnly',
      },
      {
        key: 'delegation',
        type: 'readOnly',
      },
      {
        key: 'creationDate',
        type: 'date',
      },
    ];

    this.dataSource.data = [
      {
        id: 'PIBR00001',
        ibrelleuProjectName: 'Paquito Chocolatero',
        projectStatus: 'Active',
        mainSector: 'Servicios',
        mainActivity: 'Otros',
        totalEconomicSituation: 2000,
        consultant: 'José Luis De Jesús',
        delegation: 'Mallorca',
        creationDate: '10/02/2025',
      },
      {
        id: 'PIBR00002',
        ibrelleuProjectName: 'Paquito Chocolatero',
        projectStatus: 'Active',
        mainSector: 'Servicios',
        mainActivity: 'Otros',
        totalEconomicSituation: 2000,
        consultant: 'José Luis De Jesús',
        delegation: 'Mallorca',
        creationDate: '10/02/2025',
      },
      {
        id: 'PIBR00003',
        ibrelleuProjectName: 'Paquito Chocolatero',
        projectStatus: 'Active',
        mainSector: 'Servicios',
        mainActivity: 'Otros',
        totalEconomicSituation: 2000,
        consultant: 'José Luis De Jesús',
        delegation: 'Mallorca',
        creationDate: '10/02/2025',
      },
      {
        id: 'PIBR00004',
        ibrelleuProjectName: 'Paquito Chocolatero',
        projectStatus: 'Active',
        mainSector: 'Servicios',
        mainActivity: 'Otros',
        totalEconomicSituation: 2000,
        consultant: 'José Luis De Jesús',
        delegation: 'Mallorca',
        creationDate: '10/02/2025',
      },
      {
        id: 'PIBR00005',
        ibrelleuProjectName: 'Paquito Chocolatero',
        projectStatus: 'Active',
        mainSector: 'Servicios',
        mainActivity: 'Otros',
        totalEconomicSituation: 2000,
        consultant: 'José Luis De Jesús',
        delegation: 'Mallorca',
        creationDate: '10/02/2025',
      },
      {
        id: 'PIBR00006',
        ibrelleuProjectName: 'Paquito Chocolatero',
        projectStatus: 'Active',
        mainSector: 'Servicios',
        mainActivity: 'Otros',
        totalEconomicSituation: 2000,
        consultant: 'José Luis De Jesús',
        delegation: 'Mallorca',
        creationDate: '10/02/2025',
      },
      {
        id: 'PIBR00007',
        ibrelleuProjectName: 'Paquito Chocolatero',
        projectStatus: 'Active',
        mainSector: 'Servicios',
        mainActivity: 'Otros',
        totalEconomicSituation: 2000,
        consultant: 'José Luis De Jesús',
        delegation: 'Mallorca',
        creationDate: '10/02/2025',
      },
      {
        id: 'PIBR00008',
        ibrelleuProjectName: 'Paquito Chocolatero',
        projectStatus: 'Active',
        mainSector: 'Servicios',
        mainActivity: 'Otros',
        totalEconomicSituation: 2000,
        consultant: 'José Luis De Jesús',
        delegation: 'Mallorca',
        creationDate: '10/02/2025',
      },
      {
        id: 'PIBR00009',
        ibrelleuProjectName: 'Paquito Chocolatero',
        projectStatus: 'Active',
        mainSector: 'Servicios',
        mainActivity: 'Otros',
        totalEconomicSituation: 2000,
        consultant: 'José Luis De Jesús',
        delegation: 'Mallorca',
        creationDate: '10/02/2025',
      },
      {
        id: 'PIBR00010',
        ibrelleuProjectName: 'Paquito Chocolatero',
        projectStatus: 'Active',
        mainSector: 'Servicios',
        mainActivity: 'Otros',
        totalEconomicSituation: 2000,
        consultant: 'José Luis De Jesús',
        delegation: 'Mallorca',
        creationDate: '10/02/2025',
      },
      {
        id: 'PIBR00011',
        ibrelleuProjectName: 'Paquito Chocolatero',
        projectStatus: 'Active',
        mainSector: 'Servicios',
        mainActivity: 'Otros',
        totalEconomicSituation: 2000,
        consultant: 'José Luis De Jesús',
        delegation: 'Mallorca',
        creationDate: '10/02/2025',
      },
      {
        id: 'PIBR00012',
        ibrelleuProjectName: 'Paquito Chocolatero',
        projectStatus: 'Active',
        mainSector: 'Servicios',
        mainActivity: 'Otros',
        totalEconomicSituation: 2000,
        consultant: 'José Luis De Jesús',
        delegation: 'Mallorca',
        creationDate: '10/02/2025',
      },
      {
        id: 'PIBR00013',
        ibrelleuProjectName: 'Paquito Chocolatero',
        projectStatus: 'Active',
        mainSector: 'Servicios',
        mainActivity: 'Otros',
        totalEconomicSituation: 2000,
        consultant: 'José Luis De Jesús',
        delegation: 'Mallorca',
        creationDate: '10/02/2025',
      },
      {
        id: 'PIBR00014',
        ibrelleuProjectName: 'Paquito Chocolatero',
        projectStatus: 'Active',
        mainSector: 'Servicios',
        mainActivity: 'Otros',
        totalEconomicSituation: 2000,
        consultant: 'José Luis De Jesús',
        delegation: 'Mallorca',
        creationDate: '10/02/2025',
      },
      {
        id: 'PIBR00015',
        ibrelleuProjectName: 'Paquito Chocolatero',
        projectStatus: 'Active',
        mainSector: 'Servicios',
        mainActivity: 'Otros',
        totalEconomicSituation: 2000,
        consultant: 'José Luis De Jesús',
        delegation: 'Mallorca',
        creationDate: '10/02/2025',
      },
      {
        id: 'PIBR00016',
        ibrelleuProjectName: 'Paquito Chocolatero',
        projectStatus: 'Active',
        mainSector: 'Servicios',
        mainActivity: 'Otros',
        totalEconomicSituation: 2000,
        consultant: 'José Luis De Jesús',
        delegation: 'Mallorca',
        creationDate: '10/02/2025',
      },
      {
        id: 'PIBR00017',
        ibrelleuProjectName: 'Paquito Chocolatero',
        projectStatus: 'Active',
        mainSector: 'Servicios',
        mainActivity: 'Otros',
        totalEconomicSituation: 2000,
        consultant: 'José Luis De Jesús',
        delegation: 'Mallorca',
        creationDate: '10/02/2025',
      },
      {
        id: 'PIBR00018',
        ibrelleuProjectName: 'Paquito Chocolatero',
        projectStatus: 'Active',
        mainSector: 'Servicios',
        mainActivity: 'Otros',
        totalEconomicSituation: 2000,
        consultant: 'José Luis De Jesús',
        delegation: 'Mallorca',
        creationDate: '10/02/2025',
      },
      {
        id: 'PIBR00019',
        ibrelleuProjectName: 'Paquito Chocolatero',
        projectStatus: 'Active',
        mainSector: 'Servicios',
        mainActivity: 'Otros',
        totalEconomicSituation: 2000,
        consultant: 'José Luis De Jesús',
        delegation: 'Mallorca',
        creationDate: '10/02/2025',
      },
      {
        id: 'PIBR00020',
        ibrelleuProjectName: 'Paquito Chocolatero',
        projectStatus: 'Active',
        mainSector: 'Servicios',
        mainActivity: 'Otros',
        totalEconomicSituation: 2000,
        consultant: 'José Luis De Jesús',
        delegation: 'Mallorca',
        creationDate: '10/02/2025',
      },
    ];

    this.columnsDisplayed = this.columnsSchema.map((col: any) => col.key);
  }
}
